'use client';
import { useEffect, useRef, useState } from 'react';
import styles from './tickets.module.css';
type Prize={name:string;description:string;kind:'percentage_off'|'amount_off'|'manual'|'none';value:number;quantity:number};
type Pool={id:string;title:string;mode:string;state:string;quantity:number;per_user:number;config?:{prizes:Omit<Prize,'quantity'>[]}};
type Code={code:string;capacity:number;claimed:number};
type Manual={id:string;user_id:string;prize:Prize;manual_state:string};
async function api(path:string,body?:unknown,key?:string){const response=await fetch(`/api/tickets/${path}`,{cache:'no-store',method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json',...(key?{'Idempotency-Key':key}:{})},...(body===undefined?{}:{body:JSON.stringify(body)})});const data=await response.json();if(!response.ok)throw Error(({permission_denied:'Your staff role does not permit this action.',conflict:'This request conflicts with a saved version. Refresh before continuing.',invalid_input:'Check the inventory and limits.'} as Record<string,string>)[data.error]??'The operation could not be confirmed. Refresh to check its status.');return data;}
const blank=():Prize=>({name:'',description:'',kind:'percentage_off',value:20,quantity:1});
export function TicketConsole(){
 const [pools,setPools]=useState<Pool[]>([]),[manual,setManual]=useState<Manual[]>([]),[selected,setSelected]=useState<Pool|null>(null),[codes,setCodes]=useState<Code[]>([]),[page,setPage]=useState(0),[codePage,setCodePage]=useState(0),[manualPage,setManualPage]=useState(0),[title,setTitle]=useState(''),[mode,setMode]=useState('shared'),[limit,setLimit]=useState(1),[prizes,setPrizes]=useState<Prize[]>([blank()]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[loaded,setLoaded]=useState(false),[references,setReferences]=useState<Record<string,string>>({});
 const request=useRef<{payload:string;id:string}|null>(null);
 const quantity=prizes.reduce((n,p)=>n+p.quantity,0);
 async function load(){const [p,m]=await Promise.all([api(`pools?page=${page}`),api(`manual?page=${manualPage}`)]);setPools(p.items);setManual(m.items);setLoaded(true);}
 useEffect(()=>{let active=true;Promise.all([api(`pools?page=${page}`),api(`manual?page=${manualPage}`)]).then(([p,m])=>{if(active){setPools(p.items);setManual(m.items);setLoaded(true);}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[page,manualPage]);
 async function run(fn:()=>Promise<void>){setBusy(true);setError('');setNotice('');try{await fn();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function inspect(id:string,p=0){const data=await api(`pools/${id}?page=${p}`);setSelected(data.item);setCodes(data.codes);setCodePage(p);}
 function update(index:number,changes:Partial<Prize>){setPrizes(rows=>rows.map((row,i)=>i===index?{...row,...changes}:row));}
 async function save(){if(quantity<1||quantity>2000||limit<1||limit>quantity)throw Error('Choose 1–2,000 tickets and a per-person limit within that total.');const body={title,mode,per_user:limit,prizes:prizes.flatMap(({quantity,...prize})=>Array.from({length:quantity},()=>prize))};const payload=JSON.stringify(body);if(request.current?.payload!==payload)request.current={payload,id:crypto.randomUUID()};const result=await api('pools',body,request.current.id);await load();await inspect(result.id);setNotice('Draft created. Review the exact inventory below, then activate the collection.');}
 async function download(){if(!selected)return;const all:Code[]=[];for(let p=0;p<20;p++){const data=await api(`pools/${selected.id}?page=${p}`);all.push(...data.codes);if(data.codes.length<100)break;}const blob=new Blob(['code,capacity,claimed\n'+all.map(c=>`${c.code},${c.capacity},${c.claimed}`).join('\n')],{type:'text/csv'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`ticket-codes-${selected.id}.csv`;a.click();URL.revokeObjectURL(url);}
 return <main className={styles.console}><header><p className={styles.eyebrow}>Rewards / exact inventory</p><h1>Ticket collections</h1><p>Choose every prize, then distribute the collection with one shared code or individual codes.</p></header>{error&&<p className={styles.error} role="alert">{error}</p>}{notice&&<p role="status" className={styles.notice}>{notice}</p>}
 <section className={styles.editor}><h2>Create a collection</h2><form onSubmit={e=>{e.preventDefault();void run(save);}}><div className={styles.settings}><label>Collection name<input value={title} onChange={e=>setTitle(e.target.value)} maxLength={100} required/></label><label>Distribution<select value={mode} onChange={e=>setMode(e.target.value)}><option value="shared">One shared code</option><option value="individual">One code per ticket</option><option value="reward">Weekly puzzle rewards</option></select></label><label>Tickets per person<input type="number" min={1} max={Math.max(1,quantity)} value={limit} onChange={e=>setLimit(Number(e.target.value))} required/></label></div>
 <div className={styles.inventoryHeader}><h3>Choose the prizes</h3><span>{quantity} / 2,000 tickets</span></div><p className={styles.hint}>Each row adds exactly that many prizes. To choose ten different prizes, add ten rows with quantity 1. Use 100% off for a free checkout.</p>
 {prizes.map((p,i)=><fieldset className={styles.prize} key={i}><legend>Prize {i+1}</legend><div className={styles.prizeFields}><label>Name<input value={p.name} maxLength={80} required onChange={e=>update(i,{name:e.target.value})}/></label><label>Type<select value={p.kind} onChange={e=>update(i,{kind:e.target.value as Prize['kind'],value:['none','manual'].includes(e.target.value)?0:20})}><option value="percentage_off">Percentage discount</option><option value="amount_off">Dollar discount (cents)</option><option value="manual">Custom prize / staff fulfillment</option><option value="none">No prize</option></select></label>{!['none','manual'].includes(p.kind)&&<label>{p.kind==='percentage_off'?'Percent off':'Discount in cents'}<input type="number" min={1} max={p.kind==='percentage_off'?100:10000000} required value={p.value} onChange={e=>update(i,{value:Number(e.target.value)})}/></label>}<label>Quantity<input type="number" min={1} max={2000} required value={p.quantity} onChange={e=>update(i,{quantity:Number(e.target.value)})}/></label></div><label>Prize details<input value={p.description} maxLength={400} onChange={e=>update(i,{description:e.target.value})}/></label><div className={styles.rowFooter}><span>{quantity?((p.quantity/quantity)*100).toFixed(2):0}% of this collection</span><button type="button" disabled={prizes.length===1||busy} onClick={()=>setPrizes(rows=>rows.filter((_,index)=>i!==index))}>Remove prize</button></div></fieldset>)}
 <div className={styles.actions}><button type="button" disabled={prizes.length>=2000||busy} onClick={()=>setPrizes(rows=>[...rows,blank()])}>Add prize</button><button className={styles.primary} disabled={busy||quantity<1||quantity>2000}>Create draft with {quantity} tickets</button></div><p className={styles.hint}>Prizes are assigned once. The saved inventory cannot be edited or rerolled. Pause a collection to stop new claims; already claimed tickets remain valid.</p></form></section>
 <section><h2>Saved collections</h2>{!loaded&&!error&&<p>Loading collections…</p>}{loaded&&!pools.length&&<p>No collections yet.</p>}<div className={styles.tableWrap}><table><thead><tr><th>Collection</th><th>Tickets</th><th>Distribution</th><th>Status</th><th>Review</th></tr></thead><tbody>{pools.map(p=><tr key={p.id}><td>{p.title}</td><td>{p.quantity}</td><td>{p.mode}</td><td>{p.state}</td><td><button disabled={busy} onClick={()=>void run(()=>inspect(p.id))}>Open</button></td></tr>)}</tbody></table></div><div className={styles.actions}><button disabled={page===0||busy} onClick={()=>setPage(p=>p-1)}>Previous collections</button><button disabled={pools.length<50||busy} onClick={()=>setPage(p=>p+1)}>Next collections</button></div></section>
 {selected&&<section className={styles.review}><div className={styles.inventoryHeader}><h2>{selected.title}</h2><span>{selected.state}</span></div><p>{selected.quantity} tickets · {selected.per_user} per person · {selected.mode==='shared'?'One shared code':selected.mode==='individual'?`${selected.quantity} individual codes`:'Puzzle reward inventory'}</p><p className={styles.hint}>Collection ID for puzzles: <code>{selected.id}</code></p><details><summary>Review all {selected.quantity} chosen prizes</summary><ol>{selected.config?.prizes.map((p,i)=><li key={i}>{p.name} — {p.kind==='percentage_off'?`${p.value}% off`:p.kind==='amount_off'?`$${(p.value/100).toFixed(2)} off`:p.kind==='manual'?'Staff fulfillment':'No prize'}{p.description?` · ${p.description}`:''}</li>)}</ol></details><div className={styles.actions}><button disabled={busy} className={styles.primary} onClick={()=>void run(async()=>{await api(`pools/${selected.id}/state`,{state:selected.state==='active'?'paused':'active'});await inspect(selected.id);await load();setNotice(selected.state==='active'?'New claims paused.':'Collection activated. The saved prizes are fixed.');})}>{selected.state==='active'?'Pause new claims':'Activate collection'}</button>{selected.mode!=='reward'&&<button disabled={busy} onClick={()=>void run(download)}>Download all codes</button>}</div>{selected.mode!=='reward'&&<><p>Share codes only with intended recipients. Prize assignments are never included in this list.</p><ul className={styles.codes}>{codes.map(c=><li key={c.code}><code>{c.code}</code><span>{c.claimed}/{c.capacity} claimed</span></li>)}</ul><div className={styles.actions}><button disabled={codePage===0||busy} onClick={()=>void run(()=>inspect(selected.id,codePage-1))}>Previous codes</button><button disabled={codes.length<100||busy} onClick={()=>void run(()=>inspect(selected.id,codePage+1))}>Next codes</button></div></>}</section>}
 <section><h2>Custom prize requests</h2><p>Arrange delivery with the customer, then record your fulfillment reference.</p>{manual.length===0&&loaded&&<p>No custom prize requests on this page.</p>}{manual.map(m=><form className={styles.manual} key={m.id} onSubmit={e=>{e.preventDefault();void run(async()=>{await api(`manual/${m.id}`,{reference:references[m.id]});await load();setNotice('Prize fulfillment recorded.');});}}><div><strong>{m.prize.name}</strong><p>Customer: {m.user_id}</p><p>{m.prize.description}</p></div>{m.manual_state==='completed'?<span>Fulfilled</span>:<><label>Fulfillment reference<input required maxLength={200} value={references[m.id]??''} onChange={e=>setReferences(r=>({...r,[m.id]:e.target.value}))}/></label><button disabled={busy}>Record fulfillment</button></>}</form>)}<div className={styles.actions}><button disabled={manualPage===0||busy} onClick={()=>setManualPage(p=>p-1)}>Previous requests</button><button disabled={manual.length<50||busy} onClick={()=>setManualPage(p=>p+1)}>Next requests</button></div></section></main>;
}
