begin;
insert into auth.users values('11111111-1111-4111-8111-111111111111'),('22222222-2222-4222-8222-222222222222');
do $$ declare u uuid:='11111111-1111-4111-8111-111111111111';a uuid:=gen_random_uuid();funded uuid:=gen_random_uuid();m uuid:=gen_random_uuid();p uuid:=gen_random_uuid();j jsonb;old_lease uuid;i uuid;begin
 insert into public.ct_accounts(id,user_id,vendor_id,firm_id,kind,lifecycle,vendor_updated_at) values(a,u,'awards-eval','firm','evaluation','active',now());
 update public.ct_accounts set lifecycle='passed' where id=a;
 update public.ct_accounts set lifecycle='upgraded' where id=a;
 perform public.ca_account(a);
 if(select count(*) from public.ca_issues where account_id=a)<>1 then raise exception 'duplicate pass';end if;
 if(select count(*) from public.cd_awards where user_id=u and kind='summit')<>1 then raise exception 'discord not using shared ledger';end if;
 if(select count(*) from public.cd_jobs where kind='milestone')<>1 then raise exception 'duplicate announcement';end if;
 select id into i from public.ca_issues where account_id=a;
 if(select count(*) from public.ca_renders where issue_id=i)<>1 then raise exception 'missing render';end if;
 j=public.ca_claim();old_lease=(j->>'lease')::uuid;
 update public.ca_renders set leased_at=now()-interval '4 minutes' where id=(j->>'id')::uuid;
 j=public.ca_claim();
 begin perform public.ca_finish((j->>'id')::uuid,old_lease,'stale.png',null);raise exception 'accepted stale';exception when raise_exception then if sqlerrm<>'lease_lost' then raise;end if;end;
 perform public.ca_finish((j->>'id')::uuid,(j->>'lease')::uuid,'current.png',null);
 perform public.ca_edit(u,'draft','passed',1,'{"site":"Certa"}','new wording');
 perform public.ca_edit(u,'publish','passed',2,'{}','reviewed design');
 if(select template_version from public.ca_issues where id=i)<>1 then raise exception 'issued template changed';end if;
 perform public.ca_edit(u,'correct',i::text,1,'{"name":"@TRADER"}','recipient correction');
 if(select count(*) from public.ca_renders where issue_id=i)<>2 then raise exception 'missing correction';end if;
 if(select fields->>'name' from public.ca_renders where issue_id=i and revision=1)<>'CERTA TRADER' then raise exception 'original overwritten';end if;
 perform public.ca_import_reference(u,u,'pass:'||a,'legacy-award-1','CERTA-PASS-OLD-001','verified previous ledger');
 perform public.ca_import_reference(u,u,'pass:'||a,'legacy-award-1','CERTA-PASS-OLD-001','verified previous ledger');
 if(select count(*) from public.ca_legacy_refs)<>1 or(select count(*) from public.ca_renders where issue_id=i)<>3 then raise exception 'import replay duplicated reference';end if;
 if(select fields->>'certNo' from public.ca_renders where issue_id=i and revision=3)<>'CERTA-PASS-OLD-001' then raise exception 'legacy number lost';end if;
 perform public.ca_share(u,i,true,true);perform public.ca_share(u,i,true,true);
 if(select count(*) from public.ca_issues where snapshot->>'source_issue'=i::text)<>1 then raise exception 'duplicate privacy copy';end if;
 if(select fields->>'name' from public.ca_issues where snapshot->>'source_issue'=i::text)<>'HIDDEN' then raise exception 'privacy masking failed';end if;
 perform public.cd_founding(u,u,'verified cohort');perform public.cd_founding(u,u,'verified cohort retry');
 if(select count(*) from public.ca_issues where award_id='ribbon')<>1 then raise exception 'duplicate coin';end if;
 insert into public.ct_accounts(id,user_id,vendor_id,firm_id,kind,lifecycle) values(funded,u,'awards-funded','firm','funded','active');
 insert into public.cp_methods(id,user_id,kind,label,masked,encrypted) values(m,u,'bank','Bank','1234','fixture');
 insert into public.cp_payouts(id,user_id,kind,account_id,method_id,method_snapshot,amount_cents,state,paid_at) values(p,u,'trader',funded,m,'{}',50000,'paid',now());
 perform public.ca_payout(p);
 insert into public.cp_payouts(user_id,kind,account_id,method_id,method_snapshot,amount_cents,state,paid_at) values(u,'trader',funded,m,'{}',70000,'paid',now());
 if(select count(*) from public.ca_issues where account_id=funded and award_id='bronze')<>1 or(select count(*) from public.ca_issues where account_id=funded and award_id='crown')<>1 then raise exception 'incorrect payout cycle';end if;
 if(select snapshot->>'amount_cents' from public.ca_issues where payout_id=p)<>'50000' then raise exception 'wrong amount snapshot';end if;
end $$;
set local role authenticated;
do $$ begin
 begin perform * from public.ca_issues;raise exception 'client read';exception when insufficient_privilege then null;end;
 begin perform * from public.cd_awards;raise exception 'client view read';exception when insufficient_privilege then null;end;
 begin perform public.ca_claim();raise exception 'client claim';exception when insufficient_privilege then null;end;
end $$;
reset role;
rollback;
