begin;
insert into auth.users values('11111111-1111-4111-8111-111111111111'),('22222222-2222-4222-8222-222222222222');
select public.ct_lease('discord-worker','discord-test');
do $$ declare u uuid:='11111111-1111-4111-8111-111111111111';v uuid:='22222222-2222-4222-8222-222222222222';e uuid;j jsonb;a uuid:=gen_random_uuid();m uuid;funded uuid;begin
 perform public.cd_oauth_begin(u,'state-a');e:=public.cd_oauth_consume(u,'state-a');
 begin perform public.cd_oauth_consume(u,'state-a');raise exception 'unexpected replay';exception when raise_exception then if sqlerrm<>'oauth_expired' then raise;end if;end;
 perform public.cd_link(u,e,'123456789012345678','Trader');
 j:=public.cd_claim('discord-test');perform public.cd_queue_roles(u);perform public.cd_finish((j->>'id')::uuid,'queued','rate_limit');
 if (select count(*) from public.cd_jobs where user_id=u and kind='roles' and state='queued')<>1 then raise exception 'role retry coalescing failed';end if;
 perform public.cd_oauth_begin(v,'state-v');e:=public.cd_oauth_consume(v,'state-v');
 begin perform public.cd_link(v,e,'123456789012345678','Trader');raise exception 'duplicate identity';exception when raise_exception then if sqlerrm<>'already_linked' then raise;end if;end;
 begin perform public.cd_oauth_begin(u,'state-b');raise exception 'duplicate user';exception when raise_exception then if sqlerrm<>'already_linked' then raise;end if;end;
 insert into public.ct_accounts(id,user_id,vendor_id,firm_id,kind,lifecycle) values(a,u,'discord-account','firm','evaluation','active');
 update public.ct_accounts set lifecycle='passed' where id=a;
 update public.ct_accounts set lifecycle='upgraded' where id=a;
 if (select count(*) from public.cd_jobs where kind='milestone')<>1 then raise exception 'duplicate pass event';end if;
 perform public.cd_config_role(v,'summit','345678901234567890','test mapping');perform public.cd_config_role(v,'funded','456789012345678901','test mapping');
 if not public.cd_roles_wanted(u) ? '345678901234567890' or public.cd_roles_wanted(u) ? '456789012345678901' then raise exception 'pass confused with funded';end if;
 insert into public.ct_accounts(user_id,vendor_id,firm_id,kind,lifecycle) values(u,'discord-funded','firm','funded','active');
 if not public.cd_roles_wanted(u) ? '456789012345678901' then raise exception 'funded role missing';end if;
 update public.ct_accounts set lifecycle='closed' where vendor_id='discord-funded';
 if public.cd_roles_wanted(u) ? '456789012345678901' then raise exception 'closed account retains funded role';end if;
 select id into funded from public.ct_accounts where vendor_id='discord-funded';
 insert into public.cp_methods(user_id,kind,label,masked,encrypted) values(u,'bank','Fixture','1234','fixture') returning id into m;
 insert into public.cp_payouts(user_id,kind,account_id,method_id,method_snapshot,amount_cents,state) values(u,'trader',funded,m,'{}',25000,'paid');
 perform public.cd_config_role(v,'bronze','567890123456789012','test mapping');perform public.cd_config_role(v,'crown','678901234567890123','test mapping');
 if not public.cd_roles_wanted(u) ? '567890123456789012' or public.cd_roles_wanted(u) ? '678901234567890123' then raise exception 'first payout role incorrect';end if;
 insert into public.cp_payouts(user_id,kind,account_id,method_id,method_snapshot,amount_cents,state) values(u,'trader',funded,m,'{}',25000,'paid');
 update public.cp_payouts set state='paid' where user_id=u;
 if not public.cd_roles_wanted(u) ? '678901234567890123' then raise exception 'repeat payout role missing';end if;
 if (select count(*) from public.cd_jobs where payload->>'event'='payout_paid')<>2 then raise exception 'payout events duplicated';end if;
 perform public.cd_preferences(u,true,true,false);
 insert into public.ct_records(account_id,user_id,kind,vendor_id,data,vendor_updated_at) values(a,u,'daily-stats','discord-day',jsonb_build_object('items',jsonb_build_array(jsonb_build_object('session_date',((now() at time zone 'America/Toronto')::date-1)::text,'net_pnl','250.00'))),now());
 perform public.cd_daily(u);perform public.cd_daily(u);
 if (select count(*) from public.cd_jobs where kind='daily')<>1 then raise exception 'daily duplicates';end if;
 perform public.cd_disconnect(v,u,'Staff requested unlink');
 if (select state from public.cd_links where user_id=u)<>'disconnecting' then raise exception 'cleanup record lost';end if;
 begin perform public.cd_link(v,e,'123456789012345678','Trader');raise exception 'reserved identity stolen';exception when raise_exception then if sqlerrm<>'already_linked' then raise;end if;end;
 j:=public.cd_claim('discord-test');if j->>'kind'<>'cleanup' then raise exception 'cleanup priority missing';end if;
 perform public.cd_finish((j->>'id')::uuid,'queued','fixture_permission_failure');
 if not exists(select 1 from public.cd_links where user_id=u) then raise exception 'failed cleanup lost link';end if;
 update public.cd_jobs set next_at=now() where kind='cleanup';j:=public.cd_claim('discord-test');perform public.cd_finish((j->>'id')::uuid,'sent');
 if exists(select 1 from public.cd_links where user_id=u) then raise exception 'cleanup did not release identity';end if;
 perform public.cd_link(v,e,'123456789012345678','Trader');
 -- An in-flight OAuth callback cannot reconnect after staff disconnected it.
 perform public.cd_oauth_begin(u,'state-race');e:=public.cd_oauth_consume(u,'state-race');perform public.cd_disconnect(v,u,'Cancel pending OAuth');
 begin perform public.cd_link(u,e,'234567890123456789','Trader');raise exception 'stale OAuth restored identity';exception when raise_exception then if sqlerrm<>'oauth_expired' then raise;end if;end;
 update public.cd_jobs set state='running',started_at=now()-interval '3 minutes' where kind='milestone';
 perform public.cd_claim('discord-test');
 if exists(select 1 from public.cd_jobs where kind='milestone' and state<>'unknown') then raise exception 'ambiguous post retried';end if;
 if not exists(select 1 from public.cd_audit where action='disconnect' and actor_id=v) then raise exception 'missing staff audit';end if;
end $$;
set local role authenticated;
do $$ begin
 begin perform * from public.cd_links;raise exception 'link data leaked';exception when insufficient_privilege then null;end;
 begin perform public.cd_disconnect('11111111-1111-4111-8111-111111111111','22222222-2222-4222-8222-222222222222','bypass');raise exception 'RPC exposed';exception when insufficient_privilege then null;end;
end $$;
reset role;
rollback;
