begin;
insert into auth.users values('10000000-0000-4000-8000-000000000001') on conflict do nothing;
do $$ declare u uuid='10000000-0000-4000-8000-000000000001';s uuid=gen_random_uuid();c uuid=gen_random_uuid();r jsonb; begin
 r:=public.cf_begin(u,s,'auth@example.test',c,repeat('a',64));
 if r->>'state'<>'created' then raise exception 'challenge failed'; end if;
 if public.cf_verify(u,s,'auth@example.test',c,repeat('a',64)) then raise exception 'unaccepted delivery approved';end if;
 perform public.cf_delivery(c,u,true);
 if public.cf_verify(u,gen_random_uuid(),'auth@example.test',c,repeat('a',64)) then raise exception 'cross session accepted';end if;
 if public.cf_verify(u,s,'other@example.test',c,repeat('a',64)) then raise exception 'changed email accepted';end if;
 for i in 1..5 loop if public.cf_verify(u,s,'auth@example.test',c,repeat('b',64)) then raise exception 'wrong code accepted';end if;end loop;
 if public.cf_verify(u,s,'auth@example.test',c,repeat('a',64)) then raise exception 'attempt cap bypass';end if;
 update public.cf_challenges set created_at=now()-interval '16 minutes' where id=c;
 c:=gen_random_uuid();perform public.cf_begin(u,s,'auth@example.test',c,repeat('c',64));perform public.cf_delivery(c,u,true);
 if not public.cf_verify(u,s,'auth@example.test',c,repeat('c',64)) then raise exception 'valid code failed';end if;
 if public.cf_verify(u,s,'auth@example.test',c,repeat('c',64)) then raise exception 'replay accepted';end if;
 if not public.cf_verified(u,s,'auth@example.test') then raise exception 'proof missing';end if;
 if public.cf_verified(u,gen_random_uuid(),'auth@example.test') then raise exception 'proof crossed sessions';end if;
 perform public.cf_clear(u,s);if public.cf_verified(u,s,'auth@example.test') then raise exception 'clear failed';end if;
 update public.cf_challenges set created_at=now()-interval '16 minutes' where user_id=u;
 c:=gen_random_uuid(); perform public.cf_begin(u,s,'auth@example.test',c,repeat('d',64)); perform public.cf_delivery(c,u,true);
 perform public.cf_clear(u,s);
 if public.cf_verify(u,s,'auth@example.test',c,repeat('d',64)) then raise exception 'logged-out challenge restored proof'; end if;
 perform public.cf_trust_factor(u,c);
 if public.cf_factors(u)<>jsonb_build_array(c) then raise exception 'trusted factor registration failed';end if;
 if public.cf_factors(gen_random_uuid())<>'[]'::jsonb then raise exception 'trusted factor crossed users';end if;
 perform public.cf_prove_totp(u,s,c);
 if not public.cf_verified_totp(u,s,c) then raise exception 'TOTP proof absent';end if;
 if public.cf_verified_totp(u,gen_random_uuid(),c) then raise exception 'TOTP proof crossed sessions';end if;
 if public.cf_verified_totp(u,s,gen_random_uuid()) then raise exception 'TOTP proof crossed factors';end if;
 perform public.cf_clear(u,s);
 if public.cf_verified_totp(u,s,c) then raise exception 'TOTP proof survived signout';end if;
 perform public.cf_remove_factor(u,c);
 if public.cf_factors(u)<>'[]'::jsonb then raise exception 'trusted factor removal failed';end if;
 if has_function_privilege('authenticated','public.cf_prove_totp(uuid,uuid,uuid)','execute') then raise exception 'client can mint TOTP proof';end if;
 if has_function_privilege('authenticated','public.cf_trust_factor(uuid,uuid)','execute') then raise exception 'client can trust its own factor';end if;
 if has_function_privilege('authenticated','public.cf_verify(uuid,uuid,text,uuid,text)','execute') then raise exception 'client can grant proof';end if;
end $$;
rollback;
