begin;
-- The disposable fixture models auth.users with an id only; production Supabase has email.
alter table auth.users add column if not exists email text;
insert into auth.users(id,email) values('50000000-0000-4000-8000-000000000001','taken@example.test') on conflict do nothing;
do $$ declare c uuid=gen_random_uuid(); r jsonb; u uuid='50000000-0000-4000-8000-000000000002'; begin
 if not public.cu_email_registered('Taken@Example.test') then raise exception 'registered email not detected'; end if;
 if public.cu_email_registered('new@example.test') then raise exception 'unknown email reported registered'; end if;
 r:=public.cu_signup_begin('new@example.test',repeat('i',64),c,repeat('a',64));
 if r->>'state'<>'created' then raise exception 'challenge begin failed'; end if;
 if (public.cu_signup_begin('new@example.test',repeat('i',64),gen_random_uuid(),repeat('a',64)))->>'state'<>'rate_limited' then raise exception 'per-email minute limit missing'; end if;
 if public.cu_signup_verify('new@example.test',c,repeat('a',64),repeat('p',64)) then raise exception 'unaccepted delivery approved'; end if;
 perform public.cu_signup_delivery(c,true);
 if public.cu_signup_verify('other@example.test',c,repeat('a',64),repeat('p',64)) then raise exception 'changed email accepted'; end if;
 for i in 1..5 loop if public.cu_signup_verify('new@example.test',c,repeat('b',64),repeat('p',64)) then raise exception 'wrong code accepted'; end if; end loop;
 if public.cu_signup_verify('new@example.test',c,repeat('a',64),repeat('p',64)) then raise exception 'attempt cap bypass'; end if;
 update public.cu_signup_challenges set created_at=now()-interval '16 minutes' where email='new@example.test';
 c:=gen_random_uuid(); perform public.cu_signup_begin('new@example.test',repeat('i',64),c,repeat('c',64)); perform public.cu_signup_delivery(c,true);
 if not public.cu_signup_verify('new@example.test',c,repeat('c',64),repeat('p',64)) then raise exception 'valid code failed'; end if;
 if public.cu_signup_verify('new@example.test',c,repeat('c',64),repeat('p',64)) then raise exception 'replay accepted'; end if;
 if public.cu_signup_claim('new@example.test',c,repeat('q',64)) then raise exception 'wrong proof claimed'; end if;
 if public.cu_signup_claim('other@example.test',c,repeat('p',64)) then raise exception 'proof crossed emails'; end if;
 if not public.cu_signup_claim('new@example.test',c,repeat('p',64)) then raise exception 'valid proof rejected'; end if;
 if public.cu_signup_claim('new@example.test',c,repeat('p',64)) then raise exception 'proof reused'; end if;
 perform public.cu_signup_release('new@example.test',c);
 if not public.cu_signup_claim('new@example.test',c,repeat('p',64)) then raise exception 'released proof not claimable'; end if;
 update public.cu_signup_challenges set verified_at=now()-interval '3 hours', claimed_at=null where id=c;
 if public.cu_signup_claim('new@example.test',c,repeat('p',64)) then raise exception 'stale proof claimed'; end if;
 insert into auth.users(id,email) values(u,'new@example.test');
 if not public.cu_username_available('Trader1') then raise exception 'free username reported taken'; end if;
 if (public.cu_register(u,'Trader1','Ada','Lovelace','ca'))->>'state'<>'registered' then raise exception 'register failed'; end if;
 if public.cu_username_available('trader1') then raise exception 'taken username reported free'; end if;
 if (public.cu_register('50000000-0000-4000-8000-000000000001','TRADER1','Other','Person','US'))->>'state'<>'username_taken' then raise exception 'duplicate username accepted'; end if;
 if (public.cu_profile(u))->>'username'<>'trader1' or (public.cu_profile(u))->>'country'<>'CA' then raise exception 'profile mismatch'; end if;
 perform public.cu_grant_session(u,c,'new@example.test');
 if not public.cf_verified(u,c,'new@example.test') then raise exception 'signup proof did not verify the first session'; end if;
 for i in 1..15 loop perform public.cu_signup_begin('ip'||i||'@example.test',repeat('z',64),gen_random_uuid(),repeat('a',64)); end loop;
 if (public.cu_signup_begin('ip16@example.test',repeat('z',64),gen_random_uuid(),repeat('a',64)))->>'state'<>'rate_limited' then raise exception 'per-address limit missing'; end if;
 if has_function_privilege('authenticated','public.cu_signup_claim(text,uuid,text)','execute') then raise exception 'client can claim proof'; end if;
 if has_function_privilege('anon','public.cu_register(uuid,text,text,text,text)','execute') then raise exception 'client can register'; end if;
 if has_function_privilege('authenticated','public.cu_grant_session(uuid,uuid,text)','execute') then raise exception 'client can grant a verified session'; end if;
 if has_table_privilege('authenticated','public.cu_profiles','select') then raise exception 'client can read profiles'; end if;
 perform public.cf_cleanup();
end $$;
rollback;
