'use client';
import Link from 'next/link';
import { useCallback, useEffect, useRef, useState } from 'react';
import styles from './tickets.module.css';
type Prize={name:string;description:string;kind:string;value:number};
type Ticket={id:string;title:string;prize:Prize|null;revealed_at:string|null;used_at:string|null;held:boolean;manual_state:string|null};
const messages:Record<string,string>={sold_out:'All tickets for this code have been claimed.',claim_limit:'You have claimed the allowed number from this collection.',not_active:'This collection is not accepting claims.',invalid_code:'Check the ticket code and try again.',unauthorized:'Sign in to view your tickets.',second_factor_required:'Complete your sign-in verification to continue.',permission_denied:'You do not have access to this action.',verified_email_required:'Verify your email before claiming a ticket.'};
async function api(path:string,body?:unknown,key?:string){const response=await fetch(`/api/tickets/${path}`,{method:body===undefined?'GET':'POST',cache:'no-store',headers:{'Content-Type':'application/json',...(key?{'Idempotency-Key':key}:{})},...(body===undefined?{}:{body:JSON.stringify(body)})});const data=await response.json();if(!response.ok)throw Error(messages[data.error]??'We could not confirm that action. Refresh your tickets before trying again.');return data;}
function ScratchFoil({reveal,disabled}:{reveal:()=>void;disabled:boolean}){
 const ref=useRef<HTMLCanvasElement>(null),distance=useRef(0),point=useRef<{x:number;y:number}|null>(null),fired=useRef(false);
 useEffect(()=>{const ctx=ref.current?.getContext('2d');if(!ctx)return;ctx.fillStyle='#D8B86D';ctx.fillRect(0,0,600,240);ctx.strokeStyle='#123522';ctx.lineWidth=2;for(let x=-240;x<600;x+=22){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x+240,240);ctx.stroke();}ctx.fillStyle='#D8B86D';ctx.fillRect(95,75,410,90);ctx.fillStyle='#06130D';ctx.font='bold 26px sans-serif';ctx.textAlign='center';ctx.fillText('YOUR SUMMIT SURPRISE',300,112);ctx.font='18px sans-serif';ctx.fillText('Scratch here to reveal',300,145);},[]);
 return <canvas ref={ref} width={600} height={240} className={styles.foil} aria-hidden="true" onPointerDown={event=>{if(disabled)return;event.currentTarget.setPointerCapture(event.pointerId);const r=event.currentTarget.getBoundingClientRect();point.current={x:(event.clientX-r.left)*600/r.width,y:(event.clientY-r.top)*240/r.height};}} onPointerUp={()=>{point.current=null;}} onPointerCancel={()=>{point.current=null;}} onPointerMove={event=>{if(disabled||!point.current||fired.current)return;const canvas=event.currentTarget,r=canvas.getBoundingClientRect(),x=(event.clientX-r.left)*600/r.width,y=(event.clientY-r.top)*240/r.height,ctx=canvas.getContext('2d');if(!ctx)return;ctx.globalCompositeOperation='destination-out';ctx.lineWidth=38;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(point.current.x,point.current.y);ctx.lineTo(x,y);ctx.stroke();distance.current+=Math.hypot(x-point.current.x,y-point.current.y);point.current={x,y};if(distance.current>900){fired.current=true;reveal();}}}/>;
}
export function TicketWallet(){
 const [items,setItems]=useState<Ticket[]>([]),[page,setPage]=useState(0),[code,setCode]=useState(''),[busy,setBusy]=useState<string|null>(null),[error,setError]=useState(''),[loaded,setLoaded]=useState(false);
 const claim=useRef<{code:string;key:string}|null>(null);
 const load=useCallback(async()=>{try{const result=await api(`mine?page=${page}`);setItems(result.items);setLoaded(true);}catch(e){setError((e as Error).message);}},[page]);
 useEffect(()=>{void load();},[load]);
 async function act(id:string,path:string,body:unknown={},key?:string){setBusy(id);setError('');try{await api(path,body,key);await load();if(id==='claim'){setCode('');claim.current=null;}}catch(e){setError((e as Error).message);}finally{setBusy(null);}}
 return <main className={styles.wallet}><header className={styles.heading}><span className={styles.eyebrow}>Certa collections</span><h1>Your tickets</h1><p>A little piece of the mountain. Claim your ticket, reveal your prize and keep it here.</p></header>
 <form className={styles.claim} onSubmit={event=>{event.preventDefault();const normalized=code.trim().toUpperCase();if(claim.current?.code!==normalized)claim.current={code:normalized,key:crypto.randomUUID()};void act('claim','claim',{code:normalized},claim.current.key);}}><label htmlFor="ticket-code">Have a ticket code?</label><div><input id="ticket-code" autoComplete="off" spellCheck={false} placeholder="CT-…" value={code} onChange={e=>setCode(e.target.value)} required maxLength={32}/><button disabled={busy!==null||!code.trim()}>{busy==='claim'?'Claiming…':'Claim ticket'}</button></div><small>A shared code gives you one ticket at a time, within the collection’s limit.</small></form>
 {error&&<p className={styles.error} role="alert">{error} <button onClick={()=>void load()}>Refresh tickets</button></p>}
 {!loaded&&!error&&<p role="status">Loading your collection…</p>}{loaded&&!items.length&&<p className={styles.empty}>Your collection is ready for its first ticket. Enter a code above or earn a ticket through a weekly puzzle.</p>}
 <section className={styles.grid} aria-label="Your ticket collection">{items.map(ticket=><article className={styles.ticket} key={ticket.id}><div className={styles.ticketTop}><span>CERTA / FIELD NOTES</span><span>{ticket.used_at?'Used':ticket.held?'Reserved':ticket.revealed_at?'Revealed':'Sealed'}</span></div><svg viewBox="0 0 600 100" className={styles.mountains} aria-hidden="true"><path d="M0 100 100 25 165 78 275 4 370 80 460 30 600 100"/><path d="m235 34 40-30 40 32-38-12z"/></svg><h2>{ticket.title}</h2><div className={styles.result}>{ticket.prize?<><h3>{ticket.prize.name}</h3><p>{ticket.prize.description}</p>{ticket.prize.kind==='percentage_off'&&<strong>{ticket.prize.value}% off</strong>}{ticket.prize.kind==='amount_off'&&<strong>${(ticket.prize.value/100).toFixed(2)} off</strong>}</>:<ScratchFoil disabled={busy!==null} reveal={()=>void act(ticket.id,`${ticket.id}/reveal`)}/>}</div><footer className={styles.ticketFooter}><span>No. {ticket.id.slice(0,8).toUpperCase()}</span>{!ticket.revealed_at?<button disabled={busy!==null} onClick={()=>void act(ticket.id,`${ticket.id}/reveal`)}>{busy===ticket.id?'Revealing…':'Reveal prize'}</button>:ticket.used_at?<span>Prize {ticket.manual_state==='completed'?'fulfilled':'used'}</span>:ticket.prize?.kind==='manual'?ticket.manual_state?<span>Prize request received</span>:<button disabled={busy!==null} onClick={()=>void act(ticket.id,`${ticket.id}/request-prize`)}>Request prize</button>:ticket.prize?.kind==='none'?<span>Thanks for taking part</span>:<Link href={`/checkout?ticket_id=${ticket.id}`}>{ticket.held?'Resume checkout':'Use at checkout'}</Link>}</footer></article>)}</section>
 <nav className={styles.paging} aria-label="Ticket pages"><button disabled={page===0||busy!==null} onClick={()=>setPage(p=>p-1)}>Previous</button><span>Page {page+1}</span><button disabled={items.length<50||busy!==null} onClick={()=>setPage(p=>p+1)}>Next</button></nav></main>;
}
