'use client';
import { useEffect, useState } from 'react';
type Row=Record<string,any>;
export function Community(){
 const [status,setStatus]=useState<Row|null>(null),[live,setLive]=useState<Row|null>(null),[accounts,setAccounts]=useState<Row[]>([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[preview,setPreview]=useState<Row|null>(null);
 async function api(path:string,body?:Row){const r=await fetch(`/api/community/${path}`,{method:body?'POST':'GET',cache:'no-store',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw new Error(d.error??'Request failed');return d;}
 useEffect(()=>{let active=true;void Promise.all([api('status'),api('accounts'),api('live')]).then(([s,a,l])=>{if(active){setStatus(s);setAccounts(a);setLive(l);}}).catch(e=>{if(active)setMessage(e.message);});const source=new EventSource('/api/community/stream');source.onmessage=e=>{try{if(active)setLive(JSON.parse(e.data));}catch{}};source.onerror=()=>{if(active)setLive(previous=>previous?{...previous,live:false,available:false}:null);};return()=>{active=false;source.close();};},[]);
 async function act(path:string,body:Row={}){setBusy(true);setMessage('');try{const r=await api(path,body);if(path==='connect'){window.location.assign(r.url);return;}if(path==='preview')setPreview(r);else{setStatus(await api('status'));setMessage('Saved. Discord updates may take a moment.');}}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 const link=status?.link;
 return <section className="community"><p className="eyebrow">Certa community</p><h1>Discord</h1><p>Connect your Discord account for community roles and optional verified result sharing.</p><p role="status">{message}</p>
 {live?.live&&<aside className="card"><strong>The Certa team is live</strong><p><a href={live.invite_url} target="_blank" rel="noreferrer">Join the conversation</a></p></aside>}
 <fieldset disabled={busy}>{!link?<button type="button" onClick={()=>void act('connect')}>Connect Discord</button>:<article className="card"><h2>{link.username}</h2><p>{link.state==='disconnecting'?'Disconnecting — role cleanup pending':link.member?'Connected to the Certa server':'Linked — join the server or refresh your roles'}</p><p><a href={status?.invite_url} target="_blank" rel="noreferrer">Open Certa Discord</a></p><p>{link.error_code}</p><button type="button" disabled={link.state!=='linked'} onClick={()=>void act('sync')}>Refresh roles</button> <button type="button" disabled={link.state!=='linked'} onClick={()=>void act('disconnect')}>Disconnect</button>
 {link.state==='linked'&&<><h3>Sharing preferences</h3><p>Firm announcements are anonymous by default. Personal sharing is optional. Account failures and compliance details stay private.</p><form key={JSON.stringify([link.daily_pnl,link.weekly_pnl,link.milestones,link.show_amount])} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void act('preferences',{daily_pnl:f.has('daily'),weekly_pnl:f.has('weekly'),milestones:f.has('milestones'),show_amount:f.has('amount')});}}><label><input type="checkbox" name="daily" defaultChecked={link.daily_pnl}/> Share my daily account PnL and amounts</label><label><input type="checkbox" name="weekly" defaultChecked={link.weekly_pnl}/> Share my weekly account recap and amounts</label><label><input type="checkbox" name="milestones" defaultChecked={link.milestones}/> Name me in future pass and payout posts</label><label><input type="checkbox" name="amount" defaultChecked={link.show_amount}/> Include payout amounts in my named posts</label><button>Save preferences</button></form>
 <form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void act('nickname',{nickname:String(f.get('nickname')??'').trim()||null});}}><label>Server nickname<input name="nickname" maxLength={32} defaultValue={link.nickname??''}/></label><button>Update nickname</button></form></>}
 </article>}
 <h2>Share a verified result</h2><p>Choose a closed trade, completed day or month. Numbers come from your stored Tradara session records; cards show the available reported sessions.</p><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const path=(e.nativeEvent as SubmitEvent).submitter?.getAttribute('value')??'preview';void act(path,{account_id:f.get('account'),period:f.get('period')});}}><label>Account<select name="account" required>{accounts.map(a=><option key={a.id} value={a.id}>{a.kind} · {a.id.slice(0,8)} · {a.lifecycle}</option>)}</select></label><label>Day, month, or trade reference<input name="period" placeholder="2026-09-14, 2026-08, or trade:ID" maxLength={106} required/></label><button value="preview">Preview</button> <button value="share" disabled={link?.state!=='linked'}>Share to Discord</button></form>
 {preview?.embeds?.map((card:Row,i:number)=><article className="card" key={i}><h3>{card.title}</h3><p>{card.description}</p><small>{card.footer?.text}</small></article>)}
 </fieldset><h2>Latest Certa milestones</h2>{!live?.feed?.length&&<p>Confirmed pass and payout announcements will appear here.</p>}{live?.feed?.map((event:Row)=><article className="card" key={event.id}><strong>{event.event==='evaluation_passed'?'A Certa trader passed an evaluation':'A Certa trader received a payout'}</strong><p><time dateTime={event.at}>{event.at}</time></p></article>)}</section>;
}
