'use client';
import {useEffect,useRef,useState} from 'react';
type Item=Record<string,any>;
async function api(path:string){const r=await fetch(`/api/awards/${path}`,{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error);return d;}
export function Cabinet(){
 const [items,setItems]=useState<Item[]>([]),[catalog,setCatalog]=useState<Item[]>([]),[accounts,setAccounts]=useState<Item[]>([]),[game,setGame]=useState<Item|null>(null),[renders,setRenders]=useState<Item[]>([]),[error,setError]=useState(''),[offset,setOffset]=useState(0),[selected,setSelected]=useState(''),[hideName,setHideName]=useState(true),[hideAmount,setHideAmount]=useState(false);const frame=useRef<HTMLIFrameElement>(null);
 useEffect(()=>{let active=true;Promise.all([api(`issues?offset=${offset}`),api('catalog'),api('accounts')]).then(([a,c,b])=>{if(active){setItems(a.items);setCatalog(c.items);setAccounts(b.items);}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[offset]);
 function configure(){if(!game||!frame.current)return;const post=(value:unknown)=>frame.current?.contentWindow?.postMessage(value,location.origin);const funded=game.funded_issued,days=game.eligibility?.qualifying_dates?.length??0;post({type:'set-board-config',mode:funded?'funded':'eval',paidPayouts:game.awards.filter((a:Item)=>['bronze','crown'].includes(a.award_id)).length,summitAward:funded?(game.awards.some((a:Item)=>a.award_id==='bronze')?'crown':'bronze'):'silver',traderName:'CERTA TRADER',look:game.look,accountId:game.account.id,greenDays:days,claimAlreadyDone:false,needsEval:false,failed:['failed','closed','breached'].includes(game.account.lifecycle)});post({type:'set-payout-eligibility',minimumMet:game.eligibility?.eligible===true,greenDaysComplete:days>=5,greenDays:days,minimumAmount:250,availableAmount:Number(game.eligibility?.maximum_cents??0)/100});post({type:'set-winning-journey',fromDay:0,toDay:funded?Math.min(5,days):game.vendor_progress.step,claimAlreadyDone:!funded});}
 useEffect(()=>{const receive=(event:MessageEvent)=>{if(event.origin!==location.origin||event.source!==frame.current?.contentWindow)return;if(event.data?.type==='certa:embed-ready')configure();};addEventListener('message',receive);configure();return()=>removeEventListener('message',receive);},[game]);
 return <section><h1>Your awards</h1>{error&&<p role="alert">{error}</p>}<h2>Account journey</h2><select aria-label="Account" onChange={e=>{setGame(null);if(e.target.value)api(`accounts/${e.target.value}/game`).then(setGame).catch(e=>setError(e.message));}}><option value="">Choose an account</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.kind} · {a.id.slice(0,8)} · {a.lifecycle}</option>)}</select>{game&&<><p>{game.account.kind==='evaluation'&&['passed','upgraded'].includes(game.account.lifecycle)?'Evaluation passed. '+(game.account.compliance_pending?'Compliance pending.':'Funded provisioning is managed separately.'):game.account.lifecycle}</p><iframe key={game.account.id} ref={frame} onLoad={configure} title="Your account journey" src="/game/index.html" sandbox="allow-scripts allow-same-origin" style={{width:'100%',height:400,border:0}}/><p>Account state as of {game.account.as_of??'awaiting vendor evidence'}. <button onClick={()=>api(`accounts/${game.account.id}/game`).then(setGame).catch(e=>setError(e.message))}>Refresh</button></p></>}
 <h2>Cabinet</h2>{items.map(a=><article key={a.id} className="card"><h3>{catalog.find(c=>c.id===a.award_id)?.name??'Performance card'}</h3><p>{catalog.find(c=>c.id===a.award_id)?.description}</p><p>{new Date(a.earned_at).toLocaleDateString()}</p><button onClick={()=>{setSelected(a.id);api(`issues/${a.id}`).then(d=>setRenders(d.renders)).catch(e=>setError(e.message));}}>View certificate</button></article>)}{!items.length&&<p>Your earned awards will appear here.</p>}<button disabled={!offset} onClick={()=>setOffset(Math.max(0,offset-50))}>Previous</button><button disabled={items.length<50} onClick={()=>setOffset(offset+50)}>Next</button>{selected&&<div><label><input type="checkbox" checked={hideName} onChange={e=>setHideName(e.target.checked)}/> Hide recipient</label><label><input type="checkbox" checked={hideAmount} onChange={e=>setHideAmount(e.target.checked)}/> Hide amount</label><button onClick={async()=>{try{const r=await fetch(`/api/awards/issues/${selected}/share`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({hide_name:hideName,hide_amount:hideAmount})});const data=await r.json();if(!r.ok)throw new Error(data.error);setSelected(data.id);setRenders((await api(`issues/${data.id}`)).renders);}catch(e){setError(e instanceof Error?e.message:'Unable to create copy');}}}>Create private sharing copy</button><button onClick={()=>api(`issues/${selected}`).then(d=>setRenders(d.renders)).catch(e=>setError(e.message))}>Refresh certificate</button></div>}{renders.map(r=><article key={r.id}><p>Certificate revision {r.revision}: {r.state}</p>{r.state==='ready'&&<><img style={{maxWidth:'100%'}} alt="Your certificate" src={`/api/awards/renders/${r.id}`}/><a href={`/api/awards/renders/${r.id}`} download>Download PNG</a></>}</article>)}</section>;
}
