'use client';
import {useEffect,useState} from 'react';
type Item=Record<string,any>;
async function api(path:string,body?:unknown){const r=await fetch(`/api/awards/${path}`,{cache:'no-store',...(body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})});const data=await r.json();if(!r.ok)throw new Error(data.error??'Request failed');return data;}
export function AwardsConsole(){
 const [tab,setTab]=useState('catalog'),[items,setItems]=useState<Item[]>([]),[selected,setSelected]=useState<Item|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[offset,setOffset]=useState(0),[user,setUser]=useState(''),[preview,setPreview]=useState(''),[copy,setCopy]=useState('{}'),[reason,setReason]=useState(''),[renders,setRenders]=useState<Item[]>([]),[handle,setHandle]=useState(''),[scene,setScene]=useState('hero'),[defaults,setDefaults]=useState<Record<string,Record<string,string>>>({});
 async function load(){setError('');const data=await api(`${tab}?offset=${offset}${tab==='issues'&&user?`&user_id=${encodeURIComponent(user)}`:''}`);setItems(data.items);if(data.defaults)setDefaults(data.defaults);}
 useEffect(()=>{let live=true;setItems([]);setSelected(null);setPreview('');if(tab==='games')return;api(`${tab}?offset=${offset}${tab==='issues'&&user?`&user_id=${encodeURIComponent(user)}`:''}`).then(d=>{if(live){setItems(d.items);if(d.defaults)setDefaults(d.defaults);}}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[tab,offset,user]);
 async function run(fn:()=>Promise<void>){setError('');setBusy(true);try{await fn();}catch(e){setError(e instanceof Error?e.message:'Request failed');}finally{setBusy(false);}}
 async function choose(item:Item){setSelected({...item});setPreview('');setCopy(JSON.stringify({...defaults[item.id],...item.copy},null,2));if(tab==='issues')await run(async()=>setRenders((await api(`issues/${item.id}`)).renders));}
 async function edit(action:string,id:string,revision:number,data:unknown){await api(`${action}/${id}`,{revision,data,reason});await load();}
 return <section className="award-admin"><h1>Awards & certificates</h1><p>Manage collectible descriptions, certificate designs, and issued records.</p><nav>{['catalog','templates','issues','audit','games'].map(t=><button key={t} onClick={()=>{setTab(t);setOffset(0);}} aria-pressed={tab===t}>{t}</button>)}</nav>{error&&<p role="alert">{error}</p>}
 {tab==='games'?<><label>Scene <select value={scene} onChange={e=>setScene(e.target.value)}>{['hero','climb','firm','signup','cabinet','customize'].map(m=><option key={m}>{m}</option>)}</select></label><p>Demonstration only. No awards or accounts are issued by these scenes.</p><iframe title="Game scene preview" src={`/game/index.html?mode=${scene}&trophy=1&bronze=1&crown=1&ribbon=1&steps=5`} sandbox="allow-scripts allow-same-origin"/></>:<>
 {tab==='issues'&&<label>Filter by Certa user ID<input value={user} onChange={e=>{setUser(e.target.value);setOffset(0);}}/></label>}
 <div className="award-columns"><div className="award-list">{items.map(item=><button key={`${item.id}:${item.version??''}`} onClick={()=>void choose(item)}><strong>{item.name??item.award_id??item.template_id??item.action??item.id}</strong><span>{item.version?`Version ${item.version} · ${item.state}`:item.earned_at??item.created_at??item.kicker}</span></button>)}{!items.length&&<p>No records to show.</p>}</div>
 <div>{selected&&tab==='catalog'&&<><h2>{selected.name}</h2><iframe title={`${selected.name} 3D preview`} src={`/game/index.html?mode=trinket&model=${encodeURIComponent(selected.id)}`} sandbox="allow-scripts allow-same-origin"/>{['name','kicker','description','instructions'].map(k=><label key={k}>{k}<textarea value={selected[k]} onChange={e=>setSelected({...selected,[k]:e.target.value})}/></label>)}<label>Display order<input type="number" min="0" max="1000" value={selected.display_order} onChange={e=>setSelected({...selected,display_order:Number(e.target.value)})}/></label><p>Earning rule: {selected.rule}. Description changes do not alter eligibility.</p><button disabled={busy} onClick={()=>void run(async()=>{await edit('catalog',selected.id,selected.revision,Object.fromEntries(['name','kicker','description','instructions','display_order'].map(k=>[k,selected[k]])));setSelected(null);})}>Save description</button></>}
 {selected&&tab==='templates'&&<><h2>{selected.id} · version {selected.version}</h2><p>{selected.state}. Edit the text fields below to create a new draft. Issued certificates keep their original version.</p>{Object.entries(JSON.parse(copy) as Record<string,string>).map(([key,value])=><label key={key}>{key}<input value={value} maxLength={200} onChange={e=>setCopy(JSON.stringify({...JSON.parse(copy),[key]:e.target.value}))}/></label>)}<div className="actions"><button disabled={busy} onClick={()=>void run(async()=>setPreview((await api('preview',{template:selected.id,copy:JSON.parse(copy)})).image))}>Render preview</button><button disabled={busy} onClick={()=>void run(async()=>{await edit('draft',selected.id,selected.version,JSON.parse(copy));setSelected(null);})}>Save new draft</button>{selected.state==='draft'&&<button disabled={busy} onClick={()=>void run(async()=>{await edit('publish',selected.id,selected.version,{});setSelected(null);})}>Publish version</button>}</div>{preview&&<img alt="Sample certificate — not issued" src={preview}/>}</>}
 {selected&&tab==='issues'&&<><h2>Issued record</h2><dl>{['id','user_id','award_id','source','account_id','payout_id','earned_at'].map(k=><div key={k}><dt>{k}</dt><dd>{selected[k]??'—'}</dd></div>)}</dl><h3>Certificate revisions</h3>{renders.map(r=><article key={r.id}><p>Revision {r.revision} · {r.state} · template v{r.template_version}</p>{r.state==='ready'&&<><img alt={`Certificate revision ${r.revision}`} src={`/api/awards/renders/${r.id}`}/><a href={`/api/awards/renders/${r.id}`} download>Download PNG</a></>}{r.state==='failed'&&<button disabled={busy} onClick={()=>void run(async()=>{await edit('retry',r.id,1,{});setRenders((await api(`issues/${selected.id}`)).renders);})}>Retry rendering</button>}</article>)}{renders.length>0&&<><label>Correct public recipient handle<input value={handle} maxLength={60} onChange={e=>setHandle(e.target.value)}/></label><button disabled={busy} onClick={()=>void run(async()=>{await edit('correct',selected.id,renders[0].revision,{handle,name:handle});setRenders((await api(`issues/${selected.id}`)).renders);})}>Issue corrected revision</button></>}<button disabled={busy} onClick={()=>void run(async()=>setRenders((await api(`issues/${selected.id}`)).renders))}>Refresh render status</button></>}
 {selected&&tab==='audit'&&<pre>{JSON.stringify(selected,null,2)}</pre>}</div></div>
 <div className="actions"><button disabled={offset===0||busy||tab==='catalog'} onClick={()=>setOffset(Math.max(0,offset-50))}>Previous</button><button disabled={items.length<50||busy||tab==='catalog'} onClick={()=>setOffset(offset+50)}>Next</button><button disabled={busy} onClick={()=>void run(load)}>Refresh</button></div>
 <label>Reason for changes<textarea value={reason} onChange={e=>setReason(e.target.value)} maxLength={1000} placeholder="Required for every administrative change"/></label>
 {tab==='issues'&&<details><summary>Verified opening-cohort coin</summary><p>Grant once per trader using documented opening-cohort evidence.</p><label>Certa user ID<input value={user} onChange={e=>setUser(e.target.value)}/></label><button disabled={busy} onClick={()=>void run(async()=>{await api('cohort',{user_id:user,reason});await load();})}>Grant beta coin</button></details>}
 </>}
 </section>;
}
