'use client';
import { useEffect, useState } from 'react';
type Row=Record<string,any>;
export function DiscordConsole(){
 const [links,setLinks]=useState<Row[]>([]),[jobs,setJobs]=useState<Row[]>([]),[roles,setRoles]=useState<Row[]>([]),[runtime,setRuntime]=useState<Row[]>([]),[audit,setAudit]=useState<Row[]>([]);
 const [search,setSearch]=useState(''),[reason,setReason]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[filter,setFilter]=useState('failed');
 async function api(path:string,body?:Row){const r=await fetch(`/api/community/${path}`,{method:body?'POST':'GET',cache:'no-store',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});const data=await r.json();if(!r.ok)throw new Error(data.error??'Request failed');return data;}
 async function load(cursor?:string){const term=search.trim();const query=term?`${term.includes('-')?'user':'discord'}=${encodeURIComponent(term)}`:cursor?`cursor=${cursor}`:'';const [l,j,r,t,a]=await Promise.all([api(`links?${query}`),api(`jobs?state=${filter}`),api('roles'),api('runtime'),api('audit')]);setLinks(l);setJobs(j);setRoles(r);setRuntime(t);setAudit(a);}
 async function action(path?:string,body?:Row){setBusy(true);setMessage('');try{if(path)await api(path,body??{});await load();setMessage(path?'Saved. Pending work will be processed by the Discord worker.':'Refreshed.');}catch(e){setMessage(e instanceof Error?e.message:'Request failed');}finally{setBusy(false);}}
 useEffect(()=>{void action();},[]);
 const why=()=>{if(reason.trim().length<10)throw new Error('Enter a reason of at least 10 characters.');return reason.trim();};
 function manage(path:string){try{void action(path,{reason:why()});}catch(e){setMessage((e as Error).message);}}
 return <section className="discord-console"><p className="eyebrow">Community operations</p><h1>Discord</h1><p>One Discord identity per Certa user. Disconnect stops future sharing and queues managed-role cleanup. The identity remains reserved until cleanup succeeds.</p>
 <p role="status">{message}</p><fieldset disabled={busy}><label>Audit reason<input value={reason} onChange={e=>setReason(e.target.value)} placeholder="Why is this change needed?" maxLength={500}/></label>
 <form onSubmit={e=>{e.preventDefault();void action();}}><label>Find a Certa user ID or Discord ID<input value={search} onChange={e=>setSearch(e.target.value)}/></label><button>Search / refresh</button></form>
 <h2>Linked accounts</h2>{links.length===0&&<p>No matching links.</p>}{links.map(link=><article className="card" key={link.user_id}><h3>{link.username}</h3><p>Certa: <code>{link.user_id}</code><br/>Discord: <code>{link.discord_id}</code></p><p>{link.state} · {link.member?'Server member':'Membership unconfirmed'} · {link.error_code??'No sync error'}</p><p>Last sync: {link.synced_at??'Pending'}</p><div className="links"><button type="button" onClick={()=>void action(`users/${link.user_id}/sync`)} disabled={link.state!=='linked'}>Sync roles</button><button type="button" onClick={()=>manage(`users/${link.user_id}/disconnect`)} disabled={link.state!=='linked'}>Disconnect account</button></div></article>)}
 {links.length===50&&<button type="button" onClick={()=>{setBusy(true);void load(links.at(-1)!.user_id).catch(e=>setMessage(e.message)).finally(()=>setBusy(false));}}>Next 50 links</button>}
 <h2>Delivery and recovery</h2><label>Job state<select value={filter} onChange={e=>setFilter(e.target.value)}>{['failed','unknown','queued','running','sent','cancelled'].map(v=><option key={v}>{v}</option>)}</select></label><button type="button" onClick={()=>void action()}>Load jobs</button><p>For an unknown message, verify that it was not delivered before retrying. A timeout can occur after Discord accepted it.</p>
 {jobs.map(job=><article className="card" key={job.id}><strong>{job.kind} · {job.state}</strong><p><code>{job.id}</code> · attempts {job.attempts}</p><p>{job.error_code}</p>{job.message_id&&<p>Message: {job.message_id}</p>}{['failed','unknown'].includes(job.state)&&<div className="links"><button type="button" onClick={()=>manage(`jobs/${job.id}/retry`)}>Retry with evidence</button>{job.kind!=='cleanup'&&<button type="button" onClick={()=>manage(`jobs/${job.id}/cancel`)}>Cancel job</button>}</div>}</article>)}
 {jobs.length===50&&<button type="button" onClick={()=>void api(`jobs?state=${filter}&cursor=${jobs.at(-1)!.id}`).then(setJobs).catch(e=>setMessage(e.message))}>Next 50 jobs</button>}
 <h2>Role configuration</h2><p>Use dedicated Certa roles below the bot in Discord’s role hierarchy. Retired mappings remain tracked for cleanup. Requires discord:config.</p>
 {roles.map(role=><p key={role.role_id}>{role.kind}: <code>{role.role_id}</code> · {role.active?'active':'retired'}</p>)}
 <form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{void action(`roles/${f.get('kind')}`,{role_id:String(f.get('role_id')??'').trim()||null,reason:why()});}catch(e){setMessage((e as Error).message);}}}><label>Role type<select name="kind">{['connected','evaluation','funded','summit','bronze','crown','founding'].map(v=><option key={v}>{v}</option>)}</select></label><label>Discord role ID (blank retires mapping)<input name="role_id" pattern="[0-9]{17,20}"/></label><button>Save mapping</button></form>
 <h2>Opening cohort award</h2><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{void action('founding',{user_id:f.get('user'),reason:why()});}catch(e){setMessage((e as Error).message);}}}><label>Verified opening-cohort user ID<input name="user" required/></label><button>Grant founding award</button></form>
 <h2>Commands</h2><button type="button" onClick={()=>manage('commands/register')}>Register /certa and /next</button>
 </fieldset><h2>Worker / live presence</h2><pre>{JSON.stringify(runtime,null,2)}</pre><h2>Recent audit</h2>{audit.map(item=><p key={item.id}>{item.created_at} · {item.action} · {item.user_id??'configuration'} · {item.data?.reason??''}</p>)}</section>;
}
