/**
 * ISO 3166-1 alpha-2 residential countries (official English short names), generated from
 * the original app's `i18n-iso-countries` list minus uninhabited territories. Client-safe.
 */
import { STATIC_RESTRICTED_COUNTRY_CODES } from '../commerce/restricted-countries';
export type CountryOption = { code: string; name: string };
const ISO_COUNTRIES: ReadonlyArray<readonly [string, string]> = [
  ['AF', "Afghanistan"],
  ['AX', "Åland Islands"],
  ['AL', "Albania"],
  ['DZ', "Algeria"],
  ['AS', "American Samoa"],
  ['AD', "Andorra"],
  ['AO', "Angola"],
  ['AI', "Anguilla"],
  ['AG', "Antigua and Barbuda"],
  ['AR', "Argentina"],
  ['AM', "Armenia"],
  ['AW', "Aruba"],
  ['AU', "Australia"],
  ['AT', "Austria"],
  ['AZ', "Azerbaijan"],
  ['BS', "Bahamas"],
  ['BH', "Bahrain"],
  ['BD', "Bangladesh"],
  ['BB', "Barbados"],
  ['BY', "Belarus"],
  ['BE', "Belgium"],
  ['BZ', "Belize"],
  ['BJ', "Benin"],
  ['BM', "Bermuda"],
  ['BT', "Bhutan"],
  ['BO', "Bolivia"],
  ['BQ', "Bonaire, Sint Eustatius and Saba"],
  ['BA', "Bosnia and Herzegovina"],
  ['BW', "Botswana"],
  ['BR', "Brazil"],
  ['BN', "Brunei Darussalam"],
  ['BG', "Bulgaria"],
  ['BF', "Burkina Faso"],
  ['BI', "Burundi"],
  ['KH', "Cambodia"],
  ['CM', "Cameroon"],
  ['CA', "Canada"],
  ['CV', "Cape Verde"],
  ['KY', "Cayman Islands"],
  ['CF', "Central African Republic"],
  ['TD', "Chad"],
  ['CL', "Chile"],
  ['CX', "Christmas Island"],
  ['CC', "Cocos (Keeling) Islands"],
  ['CO', "Colombia"],
  ['KM', "Comoros"],
  ['CK', "Cook Islands"],
  ['CR', "Costa Rica"],
  ['CI', "Cote d'Ivoire"],
  ['HR', "Croatia"],
  ['CU', "Cuba"],
  ['CW', "Curaçao"],
  ['CY', "Cyprus"],
  ['CZ', "Czech Republic"],
  ['CD', "Democratic Republic of the Congo"],
  ['DK', "Denmark"],
  ['DJ', "Djibouti"],
  ['DM', "Dominica"],
  ['DO', "Dominican Republic"],
  ['EC', "Ecuador"],
  ['EG', "Egypt"],
  ['SV', "El Salvador"],
  ['GQ', "Equatorial Guinea"],
  ['ER', "Eritrea"],
  ['EE', "Estonia"],
  ['SZ', "Eswatini"],
  ['ET', "Ethiopia"],
  ['FK', "Falkland Islands (Malvinas)"],
  ['FO', "Faroe Islands"],
  ['FJ', "Fiji"],
  ['FI', "Finland"],
  ['FR', "France"],
  ['GF', "French Guiana"],
  ['PF', "French Polynesia"],
  ['GA', "Gabon"],
  ['GE', "Georgia"],
  ['DE', "Germany"],
  ['GH', "Ghana"],
  ['GI', "Gibraltar"],
  ['GR', "Greece"],
  ['GL', "Greenland"],
  ['GD', "Grenada"],
  ['GP', "Guadeloupe"],
  ['GU', "Guam"],
  ['GT', "Guatemala"],
  ['GG', "Guernsey"],
  ['GN', "Guinea"],
  ['GW', "Guinea-Bissau"],
  ['GY', "Guyana"],
  ['HT', "Haiti"],
  ['VA', "Holy See (Vatican City State)"],
  ['HN', "Honduras"],
  ['HK', "Hong Kong"],
  ['HU', "Hungary"],
  ['IS', "Iceland"],
  ['IN', "India"],
  ['ID', "Indonesia"],
  ['IQ', "Iraq"],
  ['IE', "Ireland"],
  ['IR', "Islamic Republic of Iran"],
  ['IM', "Isle of Man"],
  ['IL', "Israel"],
  ['IT', "Italy"],
  ['JM', "Jamaica"],
  ['JP', "Japan"],
  ['JE', "Jersey"],
  ['JO', "Jordan"],
  ['KZ', "Kazakhstan"],
  ['KE', "Kenya"],
  ['KI', "Kiribati"],
  ['XK', "Kosovo"],
  ['KW', "Kuwait"],
  ['KG', "Kyrgyzstan"],
  ['LA', "Lao People's Democratic Republic"],
  ['LV', "Latvia"],
  ['LB', "Lebanon"],
  ['LS', "Lesotho"],
  ['LR', "Liberia"],
  ['LY', "Libya"],
  ['LI', "Liechtenstein"],
  ['LT', "Lithuania"],
  ['LU', "Luxembourg"],
  ['MO', "Macao"],
  ['MG', "Madagascar"],
  ['MW', "Malawi"],
  ['MY', "Malaysia"],
  ['MV', "Maldives"],
  ['ML', "Mali"],
  ['MT', "Malta"],
  ['MH', "Marshall Islands"],
  ['MQ', "Martinique"],
  ['MR', "Mauritania"],
  ['MU', "Mauritius"],
  ['YT', "Mayotte"],
  ['MX', "Mexico"],
  ['FM', "Micronesia, Federated States of"],
  ['MD', "Moldova, Republic of"],
  ['MC', "Monaco"],
  ['MN', "Mongolia"],
  ['ME', "Montenegro"],
  ['MS', "Montserrat"],
  ['MA', "Morocco"],
  ['MZ', "Mozambique"],
  ['MM', "Myanmar"],
  ['NA', "Namibia"],
  ['NR', "Nauru"],
  ['NP', "Nepal"],
  ['NL', "Netherlands"],
  ['NC', "New Caledonia"],
  ['NZ', "New Zealand"],
  ['NI', "Nicaragua"],
  ['NE', "Niger"],
  ['NG', "Nigeria"],
  ['NU', "Niue"],
  ['NF', "Norfolk Island"],
  ['KP', "North Korea"],
  ['MP', "Northern Mariana Islands"],
  ['NO', "Norway"],
  ['OM', "Oman"],
  ['PK', "Pakistan"],
  ['PW', "Palau"],
  ['PA', "Panama"],
  ['PG', "Papua New Guinea"],
  ['PY', "Paraguay"],
  ['CN', "People's Republic of China"],
  ['PE', "Peru"],
  ['PH', "Philippines"],
  ['PL', "Poland"],
  ['PT', "Portugal"],
  ['PR', "Puerto Rico"],
  ['QA', "Qatar"],
  ['CG', "Republic of the Congo"],
  ['GM', "Republic of The Gambia"],
  ['RE', "Reunion"],
  ['RO', "Romania"],
  ['RU', "Russian Federation"],
  ['RW', "Rwanda"],
  ['BL', "Saint Barthélemy"],
  ['SH', "Saint Helena"],
  ['KN', "Saint Kitts and Nevis"],
  ['LC', "Saint Lucia"],
  ['MF', "Saint Martin (French part)"],
  ['PM', "Saint Pierre and Miquelon"],
  ['VC', "Saint Vincent and the Grenadines"],
  ['WS', "Samoa"],
  ['SM', "San Marino"],
  ['ST', "Sao Tome and Principe"],
  ['SA', "Saudi Arabia"],
  ['SN', "Senegal"],
  ['RS', "Serbia"],
  ['SC', "Seychelles"],
  ['SL', "Sierra Leone"],
  ['SG', "Singapore"],
  ['SX', "Sint Maarten (Dutch part)"],
  ['SK', "Slovakia"],
  ['SI', "Slovenia"],
  ['SB', "Solomon Islands"],
  ['SO', "Somalia"],
  ['ZA', "South Africa"],
  ['KR', "South Korea"],
  ['SS', "South Sudan"],
  ['ES', "Spain"],
  ['LK', "Sri Lanka"],
  ['PS', "State of Palestine"],
  ['SD', "Sudan"],
  ['SR', "Suriname"],
  ['SJ', "Svalbard and Jan Mayen"],
  ['SE', "Sweden"],
  ['CH', "Switzerland"],
  ['SY', "Syrian Arab Republic"],
  ['TW', "Taiwan, Province of China"],
  ['TJ', "Tajikistan"],
  ['TH', "Thailand"],
  ['MK', "The Republic of North Macedonia"],
  ['TL', "Timor-Leste"],
  ['TG', "Togo"],
  ['TK', "Tokelau"],
  ['TO', "Tonga"],
  ['TT', "Trinidad and Tobago"],
  ['TN', "Tunisia"],
  ['TR', "Türkiye"],
  ['TM', "Turkmenistan"],
  ['TC', "Turks and Caicos Islands"],
  ['TV', "Tuvalu"],
  ['UG', "Uganda"],
  ['UA', "Ukraine"],
  ['AE', "United Arab Emirates"],
  ['GB', "United Kingdom"],
  ['TZ', "United Republic of Tanzania"],
  ['US', "United States of America"],
  ['UY', "Uruguay"],
  ['UZ', "Uzbekistan"],
  ['VU', "Vanuatu"],
  ['VE', "Venezuela"],
  ['VN', "Vietnam"],
  ['VG', "Virgin Islands, British"],
  ['VI', "Virgin Islands, U.S."],
  ['WF', "Wallis and Futuna"],
  ['EH', "Western Sahara"],
  ['YE', "Yemen"],
  ['ZM', "Zambia"],
  ['ZW', "Zimbabwe"],
];
export const POPULAR_COUNTRY_CODES = ['US', 'CA', 'GB', 'AU', 'DE', 'FR', 'IT', 'JP', 'NL', 'ES', 'IE', 'NZ', 'CH', 'SG', 'AE', 'IN'];
/** Countries a trader may register from: the ISO list minus the static restricted jurisdictions. */
export const ACCEPTED_COUNTRIES: readonly CountryOption[] = ISO_COUNTRIES.filter(([code]) => !STATIC_RESTRICTED_COUNTRY_CODES.has(code)).map(([code, name]) => ({ code, name }));
export function isAcceptedCountry(code: unknown): code is string {
  return typeof code === 'string' && /^[A-Z]{2}$/.test(code) && ACCEPTED_COUNTRIES.some(country => country.code === code);
}
export function flagEmoji(code: string) {
  return /^[A-Z]{2}$/.test(code) ? code.replace(/./g, char => String.fromCodePoint(127397 + char.charCodeAt(0))) : '';
}
